name: Generate GitHub Snake Game Images

on:
  schedule:
    - cron: '0 0 * * *'  # daily
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: checkout dis sh1t
        uses: actions/checkout@v4

      - name: generate snake (yum)
        uses: Platane/snk@v3
        with:
          github_user_name: enessmr
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark

      - name: push svgs to guthub pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main             
          folder: assets               
