name: Generate GitHub Snake Game Images

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake Game Images
        uses: Platane/snk@v3
        with:
          github_user_name: enessmr           # replace with your GitHub username

      - name: Upload Generated Images
        uses: actions/upload-artifact@v4
        with:
          name: snake-images
          path: dist/
